Make error responses better
conductor-sdk/conductor-go pull request #156
Opened 2024-10-22 20:24 UTC by codehackerr

Currently the decompressed response body is given as a byte array Converting it to string for better readability

2024-10-22 20:28 UTC, codehackerr commented
This is a DRAFT PR for enhancing the understanding.

Decompressed HTTP responses + error ( GenericSwaggerError) object is holding byte[]. This is cryptic to read.
Here I changed one instance to string for demo purpose. We can replace the old Swagger error object, V2 may not be required.

Second request, I believe is to expose context.Context to executor, workflow etc . Currently it's already a parameter to clients. Client's description is confusing. https://orkesinternal.slack.com/archives/D075LNWQGFP/p1729627367176919

2024-10-24 11:59 UTC, shaileshpadave commented
IMO returning response in byte[] is more useful for following reasons : 

1. Flexibility in Handling Various Response Types: 
By storing the body as []byte, the API client allows for flexibility in handling various response content types. The content of an error response can vary (JSON, XML, plain text, binary, etc.), and using a byte array makes it easy to process these formats as needed.

2. Performance Considerations: 
Using a []byte instead of directly converting to a string or specific type upfront can be more efficient. Since the client may not know the format of the error response ahead of time, keeping the raw bytes gives you more control over when and how you parse it.

Also by using raw `[]byte` for the body, the generated client can remain as generic as possible and support different response types or error formats without the need for specialised error types for every API response.

2024-10-29 01:19 UTC, codehackerr commented
Few things.
- We have hard coded application/json for all resources ( so binary does not apply in general )
- Error body should be textual content ( json, plain .. whatever) .
```newErr := GenericSwaggerErrorV2{
			body:  string(responseBody),
			error: httpResponse.Status,
		} 
```
- we don't have to change the response representation. It can still be byte[]

2024-10-31 19:19 UTC, codehackerr commented on sdk/client/generic_swagger_error.go
> +func (e GenericSwaggerErrorV2) Error() string {
Won't need `GenericSwaggerErrorV2` , just for demo

2024-10-31 20:20 UTC, jmigueprieto requested changes
@codehackerr can you please add a description of what we want to achieve with this PR?

Based on what I know about this, what we want to fix is that our Client/SDK is suppressing the HTTP status code. That causes issues while debugging. How is this addressing it?

2024-10-31 20:51 UTC, codehackerr commented
The changes in this PR are based on a wrong interpretation. Closing the PR.

2024-10-31 20:52 UTC, closed without merging